version: '3'

services:
  jenkins:
    image: jenkins:alpine
    container_name: jenkins
    restart: always
    ports:
      - 10080:8080
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
